; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
; jmf277: Tested for Lab 2 with Espressif 32 platform version 7.1.0.
; jmf277: The platform setting below does not pin a version.
; jmf277: Pinning a version could be worth considering for a future template.
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino

; jmf277: Match the 115200 baud rate used in main.cpp.
monitor_speed = 115200